[package]
name = "texest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.1", features = ["derive"] }
once_cell = "1.18.0"
regex = "1.10.2"
serde_yaml = "0.9.25"
tokio = { version = "1.32.0", features = ["process", "time", "full"] }

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
rstest = "0.18.2"
