name: close-release-pr

on:
  pull_request:
    branches: ["main"]
    types: ["closed"]

jobs:
  cleanup-release:
    runs-on: ubuntu-latest
    if: "startsWith(github.head_ref, 'release/') && !github.event.pull_request.head.fork"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          TAG="v${VERSION}"
          echo target version is ${TAG}

          RELEASE=$(hub release --include-drafts -f "%T:%S%n" | grep -e "^${TAG//./\\.}:")
          if [ -z "${RELEASE}" ]; then
            echo "Release ${TAG} is not found"
            exit 1
          fi
          STATE=$(echo "${RELEASE}" | cut -d : -f 2)
          if [ "${STATE}" != draft ]; then
            echo "Release ${TAG} is already published"
            exit 0
          fi

          if [ "${{ github.event.pull_request.merged }}" = true ]; then
            echo "Publish ${TAG} from draft"
            hub release edit --draft=false -m "" "${TAG}"
          else
            echo "Delete ${TAG}"
            gh release delete "${TAG}"
          fi
