name: close-release-pr

on:
  pull_request:
    branches: ["main"]
    types: ["closed"]

jobs:
  cleanup-release:
    runs-on: ubuntu-latest
    if: "startsWith(github.head_ref, 'release/') && !github.event.pull_request.head.fork"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          TAG="v${VERSION}"
          echo target version is ${TAG}

          if [ $(gh api /repos/autopp/texest/releases | jq "any(.name == \"${TAG}\")") = false ]; then
            echo "Release ${TAG} is not found"
            exit 1
          fi
          if [ $(gh api /repos/autopp/texest/releases | jq "any(.name == \"${TAG}\" and .draft == false)") = true ]; then
            echo "Release ${TAG} is already published"
            exit 0
          fi

          if [ "${{ github.event.pull_request.merged }}" = true ]; then
            echo "Publish ${TAG} from draft"
            gh release edit "${TAG}"
          else
            echo "Delete ${TAG}"
            gh release delete "${TAG}"
          fi
      - name: Notify to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,took,workflow,job,ref,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
